# Generated by Django 4.1.6 on 2023-02-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('work', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('profileImage', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
