# Generated by Django 4.1.6 on 2023-02-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
